name: 'Merge checks'
description: 'Set a merge check status for the triggering commit to report on any problems that would block a merge.'
inputs:
  github_token:
    description: 'Token with repository permissions, e.g. secrets.GITHUB_TOKEN of the caller workflow'
    required: true

runs:

  using: "composite"

  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Build and install "merge-checks" project from pyproject.toml in current directory
    - run: pip install .
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: merge_checks_runner
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
