name: 'Merge checks'
description: 'Block merge if PR contains fixup commits or is not up to date with master'

runs:

  using: "composite"

  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - run: python3 -m merge_checks
      shell: bash
      env:
        BASE_REF: ${{ github.base_ref }}
        HEAD_REF: ${{ github.head_ref }}
        PYTHONPATH: ${{ github.action_path }}
