[tool.poetry]
name = "merge-checks"
version = "0.1.0"
description = "GitHub Merge Checks"
authors = ["moneymeets GmbH <service@moneymeets.com>"]

[tool.poetry.scripts]
merge_checks_runner = 'merge_checks.runner:run'

[tool.poetry.dependencies]
python = "^3.10"
PyGithub = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

add-trailing-comma = "*"
black = "*"
flake8 = "*"
flake8-black = "*"
flake8-coding = "*"
flake8-isort = "*"
flake8-quotes = "*"
isort = {extras = ["pyproject"], version = "*"}

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 120

[tool.coverage.run]
branch = true
source = ["."]
omit = ["tests/*.py"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
